name: Modrinth release
on: 
  push:
    tags:
      - '*'
    branches-ignore:
      - 'java-latest'
jobs:
  zip:
    runs-on: ubuntu-latest
    if: ${{github.ref_type == 'tag'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Branch
        id: get_branch
        run: |
          if [ "${{github.event_name}}" == "push" ]; then
            ref_type=$(echo "${{github.ref}}" | cut -d'/' -f2)
            if [ "$ref_type" == "heads" ]; then
              branch_name=$(echo "${{github.ref}}" | cut -d'/' -f3-)
            elif [ "$ref_type" == "tags" ]; then
              tag_name=$(echo "${{github.ref}}" | cut -d'/' -f3-)
              branch_name=$(git branch -r --contains tags/${{github.ref_name}} | grep -E -o '[^ ]+$')
            fi
          fi
          echo "branch=$branch_name" >> $GITHUB_ENV
          echo "tag=${{github.ref_name}}" >> $GITHUB_ENV
      - name: Checkout src
        uses: actions/checkout@v4
        with:
          path: src
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: afk-display-${{env.branch}}-${{env.tag}}
          path: src
      - name: Create zip file
        run: zip -r afk-display-${{env.branch}}-${{env.tag}}.zip . -x ".git/*" ".github/*" ".gitattributes" "supported_versions.txt"
        working-directory: src
      - name: Read supported versions
        uses: andstor/file-reader-action@v1
        id: read_file
        with:
          path: src/supported_versions.txt
      - name: Upload to modrinth
        uses: kir-antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{secrets.ACCESS_TOKEN}}
          modrinth-id: qKCUthaY
          name: AFK Display ${{env.branch}} ${{env.tag}}
          version: ${{env.tag}}
          files: |
            src/afk-display-${{env.branch}}-${{env.tag}}.zip
          game-versions: ${{steps.read_file.outputs.contents}}
          loaders: datapack