name: Modrinth release
on: 
  push:
    tags:
      - '*'
    branches-ignore:
      - 'java-latest'
jobs:
  zip:
    runs-on: ubuntu-latest
    if: ${{github.ref_type == 'tag'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
      - name: Get Branch
        id: get_branch
        run: |
          cd src
          branch=$(git branch -r --contains ${{github.ref}} --format "%(refname:lstrip=3)")
          echo "branch=$branch" >> $GITHUB_OUTPUT
          tag=${{github.ref_name}}
          echo "tag=$tag" >> $GITHUB_OUTPUT
          git branch -r
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: afk-display-${{steps.get_branch.outputs.branch}}-${{steps.get_branch.outputs.tag}}
          path: src
      - name: Create zip file
        run: zip -r afk-display-${{steps.get_branch.outputs.branch}}-${{steps.get_branch.outputs.tag}}.zip . -x ".git/*" ".github/*" ".gitattributes" "supported_versions.txt"
        working-directory: src
      - name: Read supported versions
        uses: andstor/file-reader-action@v1
        id: read_file
        with:
          path: src/supported_versions.txt
      - name: Upload to modrinth
        uses: kir-antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{secrets.ACCESS_TOKEN}}
          modrinth-id: qKCUthaY
          name: AFK Display ${{steps.get_branch.outputs.branch}} ${{steps.get_branch.outputs.tag}}
          version: ${{steps.get_branch.outputs.tag}}
          files: |
            src/afk-display-${{steps.get_branch.outputs.branch}}-${{steps.get_branch.outputs.tag}}.zip
          game-versions: ${{steps.read_file.outputss.contents}}
          loaders: datapack