name: Modrinth release
on: 
  push:
    tags:
      - '*'
    branches-ignore:
      - 'java-latest'
jobs:
  zip:
    runs-on: ubuntu-latest
    if: ${{github.ref_type == 'tag'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Branch
        id: get_branch
        run: |
          branch=$(curl -s -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \ https://api.github.com/repos/${{github.repository}}/git/ref/tags/${{github.ref_name}} | jq -r '.ref' | awk -F'/' '{print $3}')
          echo "branch=$branch" >> $GITHUB_ENV
          tag=${{github.ref_name}}
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Checkout src
        uses: actions/checkout@v4
        with:
          path: src
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: afk-display-${{env.branch}}-${{env.tag}}
          path: src
      - name: Create zip file
        run: zip -r afk-display-${{env.branch}}-${{env.tag}}.zip . -x ".git/*" ".github/*" ".gitattributes" "supported_versions.txt"
        working-directory: src
      - name: Read supported versions
        uses: andstor/file-reader-action@v1
        id: read_file
        with:
          path: src/supported_versions.txt
      - name: Upload to modrinth
        uses: kir-antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{secrets.ACCESS_TOKEN}}
          modrinth-id: qKCUthaY
          name: AFK Display ${{env.branch}} ${{env.tag}}
          version: ${{env.tag}}
          files: |
            src/afk-display-${{env.branch}}-${{env.tag}}.zip
          game-versions: ${{steps.read_file.outputs.contents}}
          loaders: datapack